mutation AddCard($displayName: String, $cardNumber: String, $rarityId: UUID) @auth(level: NO_ACCESS) {
    card_insert(data: { displayName: $displayName, cardNumber: $cardNumber, rarityId: $rarityId, description: "" })
}
