mutation AddCard($displayName: String, $cardNumber: String, $rarityId: UUID) @auth(expr: "auth.token.locals.role == 'admin'") {
    card_insert(data: { displayName: $displayName, cardNumber: $cardNumber, rarityId: $rarityId, description: "" })
}
