mutation AddPack($displayName: String, $setCode: String) @auth(level: NO_ACCESS) {
    query {
        sets(where: { code: { eq: $setCode  } }) {
            id
        }
    }
    pack_insert(data: { displayName: $displayName, setId_expr: "uuidV4()" })
}
