query GetPacks @auth(level: PUBLIC, insecureReason: "Packs are public data") {
    packs {
        displayName       
        set {
            code
        }
    }
}

query GetPacksAndCards @auth(level: PUBLIC, insecureReason: "Packs are public data") {
    packs {
        displayName
        set {
            code
            displayName
            releaseDate
        }
        cards_via_CardPack {
            id
            cardNumber
            displayName
            rarity {
                code
            }
        }
    }
}
