mutation AddRarity($chanceMultiplier: Float!, $displayName: String, $code: String, $description: String) @auth(expr: "auth.token.locals.role == 'admin'") {
    rarity_insert(data: { chanceMultiplier: $chanceMultiplier, displayName: $displayName, code: $code, description: $description })
}
