mutation CreateRarity($chanceMultiplier: Float!, $displayName: String, $code: String, $description: String) @auth(level: NO_ACCESS) {
    rarity_insert(data: { chanceMultiplier: $chanceMultiplier, displayName: $displayName, code: $code, description: $description })
}
