mutation AddSet($displayName: String, $code: String, $releaseDate: Date) @auth(expr: "auth.token.locals.role == 'admin'") {
    set_insert(data: { displayName: $displayName, code: $code, releaseDate: $releaseDate })
}