mutation AddCardToUser($cardId: UUID!) @auth(level: USER) {
    userCard_insert(data: { userUid_expr: "auth.uid", cardId: $cardId, quantity: 1, createdAt_expr: "request.time" })
}

mutation RemoveCardFromUser($cardId: UUID!) @auth(level: USER) {
    userCard_delete(key: { userUid_expr: "auth.uid", cardId: $cardId })
}

mutation ChangeCardQuantity($cardId: UUID!, $quantity: Int!) @auth(level: USER) {
    userCard_update(key: { userUid_expr: "auth.uid", cardId: $cardId }, data: { quantity: $quantity, lastUpdate_expr: "request.time" })
}